# Generated by Django 5.2.2 on 2025-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_record_id",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("name", models.CharField(default="Patient 1", max_length=100)),
                ("phone", models.CharField(max_length=15, null=True, unique=True)),
                ("guardian_name", models.CharField(max_length=50, null=True)),
                ("guardian_phone", models.CharField(max_length=15, null=True)),
                ("age", models.CharField(default="0", max_length=3)),
                ("gender", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "blood_group",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("image", models.TextField(blank=True, null=True)),
                ("email", models.EmailField(max_length=100, null=True, unique=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("tpa_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "tpa_validity",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("patient_history", models.JSONField(blank=True, null=True)),
                ("identity_no", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "Patients",
            },
        ),
    ]
