# Generated by Django 5.2.2 on 2025-06-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_alter_patient_aadhar_card"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="patient_recordings",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
