# Generated by Django 5.2.2 on 2025-06-21 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_remove_patient_patient_recordings"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="social_secutiry_number",
            new_name="social_security_number",
        ),
    ]
