# Generated by Django 5.2.2 on 2025-06-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0009_rename_social_security_number_patient_social_security_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="ai_report",
            field=models.TextField(blank=True, null=True),
        ),
    ]
