# Generated by Django 5.2.2 on 2025-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Billing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "billing_record_id",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("bill_type", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "service_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("amount", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "final_billing_amount",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("amount_paid", models.CharField(blank=True, max_length=50, null=True)),
                ("amount_due", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "payment_mode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("billing_address", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                ("service_details", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "Billing-General",
            },
        ),
        migrations.CreateModel(
            name="FinalBilling",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_name",
                    models.CharField(blank=True, max_length=225, null=True),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=10, null=True)),
                ("doctor_name", models.CharField(blank=True, max_length=30, null=True)),
                ("aadhar_card", models.IntegerField(blank=True, null=True)),
                (
                    "ayushman_card",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=20, null=True)),
                ("ward", models.CharField(blank=True, max_length=20, null=True)),
                ("floor", models.CharField(blank=True, max_length=10, null=True)),
                ("bed", models.CharField(blank=True, max_length=10, null=True)),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("surgeon", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "admission_purpose",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "patient_status",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "package_details",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=225, null=True)),
                (
                    "payment_type",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "total_bill_amount",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "total_paid_amount",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "total_due_amount",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "final_discount",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "final_billing_amount",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "Billing-Final",
            },
        ),
    ]
