# Generated by Django 5.2.2 on 2025-06-23 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_counter", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finalbilling",
            name="aadhar_card",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
