# Generated by Django 5.1.7 on 2025-06-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing_counter", "0004_alter_finalbilling_aadhar_card"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="final_billing_amount",
        ),
    ]
