# Generated by Django 5.1.7 on 2025-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_counter", "0005_remove_billing_final_billing_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="discount",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="billing",
            name="round_off",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
