# Generated by Django 5.1.7 on 2025-06-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing_counter", "0008_rename_amount_billing_subtotal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="billing_address",
        ),
    ]
