# Generated by Django 5.2.2 on 2025-06-25 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_counter", "0009_remove_billing_billing_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalbilling",
            name="final_dues",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
