# Generated by Django 4.2.16 on 2025-07-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_counter", "0013_alter_billing_created_at_alter_billing_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="finalbilling",
            name="billing_details",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
