# Generated by Django 5.2.2 on 2025-06-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pathology_module", "0005_remove_pathologyreports_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pathologytest",
            old_name="reference_range",
            new_name="female_reference_range",
        ),
        migrations.AddField(
            model_name="pathologytest",
            name="male_reference_range",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
