# Generated by Django 5.2.2 on 2025-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MedicineList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "medicine_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("composition", models.TextField(blank=True, null=True)),
                ("batch", models.CharField(blank=True, max_length=255, null=True)),
                ("strength", models.CharField(blank=True, max_length=255, null=True)),
                ("unit_cost", models.CharField(blank=True, max_length=255, null=True)),
                ("qty", models.CharField(blank=True, max_length=255, null=True)),
                ("total_cost", models.CharField(blank=True, max_length=255, null=True)),
                ("box_size", models.CharField(blank=True, max_length=255, null=True)),
                ("units", models.CharField(blank=True, max_length=255, null=True)),
                ("shelf", models.CharField(blank=True, max_length=255, null=True)),
                ("types", models.CharField(blank=True, max_length=255, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.TextField(blank=True, null=True)),
                ("bar_code", models.TextField(blank=True, null=True)),
                ("vendor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "manufacturer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "manufacturer_price",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("manufacturering_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("low_stock", models.CharField(blank=True, max_length=255, null=True)),
                ("gst_no", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "Pharmacy-Medicines",
            },
        ),
        migrations.CreateModel(
            name="PharmacyBill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pharmacy_bill_no",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("reg_no", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "patient_age",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "patient_phone",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "patient_gender",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "admission_purpose",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "discharge_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "ward_details",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cost", models.CharField(blank=True, max_length=255, null=True)),
                ("qty", models.CharField(blank=True, max_length=255, null=True)),
                ("amount", models.CharField(blank=True, max_length=255, null=True)),
                ("tax", models.CharField(blank=True, max_length=255, null=True)),
                ("tax_amount", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "total_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subtotal", models.CharField(blank=True, max_length=255, null=True)),
                ("discount", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "advance_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payable_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_mode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                ("medicine_details", models.JSONField(blank=True, null=True)),
            ],
            options={
                "db_table": "Pharmacy-Bill",
            },
        ),
        migrations.CreateModel(
            name="PurchaseMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "manufacturer_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("batch", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "expiry_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("mrp", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "batch_amount",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sale_price", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "packing_qty",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("qty", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "purchase_amount",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("tax", models.CharField(blank=True, max_length=10, null=True)),
                ("tax_amount", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "total_amount",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("subtotal", models.CharField(blank=True, max_length=10, null=True)),
                ("discount", models.CharField(blank=True, max_length=10, null=True)),
                ("net_amount", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "payment_mode",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "payment_amount",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "Pharmacy-Purchase",
            },
        ),
    ]
