# Generated by Django 5.2.2 on 2025-06-13 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0003_initial"),
        ("pharmacy_module", "0001_initial"),
        ("staff_management", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="medicinelist",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="medicinelist",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff_management.employee",
            ),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="medicine_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pharmacy_module.medicinelist",
            ),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="patient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="pharmacybill",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="medicine_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pharmacy_module.medicinelist",
            ),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="tenant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="purchasemedicine",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
