# Generated by Django 5.2.2 on 2025-06-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy_module", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchasemedicine",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="purchasemedicine",
            name="user",
        ),
    ]
