# Generated by Django 5.2.2 on 2025-06-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy_module", "0003_remove_purchasemedicine_tenant_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicinelist",
            name="tenant",
        ),
        migrations.RemoveField(
            model_name="medicinelist",
            name="user",
        ),
    ]
