# Generated by Django 4.2.16 on 2025-07-01 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy_module", "0004_remove_medicinelist_tenant_remove_medicinelist_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pharmacybill",
            name="admission_purpose",
        ),
        migrations.RemoveField(
            model_name="pharmacybill",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="pharmacybill",
            name="cost",
        ),
        migrations.RemoveField(
            model_name="pharmacybill",
            name="medicine_name",
        ),
        migrations.RemoveField(
            model_name="pharmacybill",
            name="qty",
        ),
        migrations.RemoveField(
            model_name="pharmacybill",
            name="reg_no",
        ),
        migrations.RemoveField(
            model_name="pharmacybill",
            name="tax",
        ),
        migrations.RemoveField(
            model_name="pharmacybill",
            name="tax_amount",
        ),
        migrations.RemoveField(
            model_name="pharmacybill",
            name="total_amount",
        ),
    ]
