# Generated by Django 5.2.2 on 2025-06-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing_counter", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PathologyTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(blank=True, max_length=100, null=True)),
                ("short_name", models.CharField(blank=True, max_length=100, null=True)),
                ("test_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sample_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_amount", models.TextField(blank=True, null=True)),
                ("precaution", models.TextField(blank=True, null=True)),
                ("title", models.JSONField(blank=True, null=True)),
                ("component_name", models.JSONField(blank=True, null=True)),
                ("component_unit", models.JSONField(blank=True, null=True)),
                ("component_result", models.JSONField(blank=True, null=True)),
                ("test_status", models.JSONField(blank=True, null=True)),
                ("reference_range", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "Patho-Test",
            },
        ),
        migrations.CreateModel(
            name="PathologyReports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "laboratory_doctor",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("report_days", models.CharField(blank=True, max_length=10, null=True)),
                ("report_date", models.CharField(blank=True, max_length=10, null=True)),
                ("test_details", models.JSONField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("total_amounts", models.TextField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("service", models.CharField(blank=True, max_length=225, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                (
                    "bill",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pathology_reports",
                        to="billing_counter.billing",
                    ),
                ),
            ],
            options={
                "db_table": "Patho-Reports",
            },
        ),
    ]
