# Generated by Django 5.2.2 on 2025-06-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="identity_no",
            new_name="ayushman_card",
        ),
        migrations.AddField(
            model_name="patient",
            name="aadhar_card",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="patient",
            name="social_secutiry_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="tpa_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="tpa_validity",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
