# Generated by Django 5.2.2 on 2025-06-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_rename_identity_no_patient_ayushman_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="aadhar_card",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
