# Generated by Django 5.2.2 on 2025-06-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "patients",
            "0008_rename_social_secutiry_number_patient_social_security_number",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="patient",
            old_name="social_security_number",
            new_name="social_security_no",
        ),
    ]
