# Generated by Django 5.2.2 on 2025-06-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0011_alter_patient_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="patient_record_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
