# Generated by Django 5.1.7 on 2025-06-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing_counter", "0006_billing_discount_billing_round_off"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billing",
            old_name="discount",
            new_name="discount_percentage",
        ),
    ]
