# Generated by Django 5.1.7 on 2025-06-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing_counter", "0007_rename_discount_billing_discount_percentage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billing",
            old_name="amount",
            new_name="subtotal",
        ),
    ]
