# Generated by Django 5.2.2 on 2025-06-25 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing_counter", "0010_finalbilling_final_dues"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finalbilling",
            old_name="final_dues",
            new_name="ipd_bed_charges",
        ),
        migrations.AddField(
            model_name="finalbilling",
            name="ipd_misc_charges",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="finalbilling",
            name="ipd_service_charges",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
