# Generated by Django 5.2.2 on 2025-07-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "billing_counter",
            "0011_rename_final_dues_finalbilling_ipd_bed_charges_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="updated_at",
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
