# Generated by Django 5.2.2 on 2025-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="service",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
