# Generated by Django 5.2.2 on 2025-06-13 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cms", "0001_initial"),
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="contactform",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contact_submissions",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="feature",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="features",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="footersettings",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footer_settings",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="gallery",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gallery_images",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="landingpagesection",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="landing_sections",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="menucategory",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_categories",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="cms.menucategory",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="cms.menuitem",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authored_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="page",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pages",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="sociallink",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_links",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="usefullink",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="useful_links",
                to="users.tenant",
            ),
        ),
        migrations.AddField(
            model_name="websitesettings",
            name="tenant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="website_settings",
                to="users.tenant",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="landingpagesection",
            unique_together={("tenant", "section_type")},
        ),
        migrations.AlterUniqueTogether(
            name="menucategory",
            unique_together={("tenant", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="page",
            unique_together={("tenant", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="sociallink",
            unique_together={("tenant", "platform")},
        ),
    ]
