# Generated by Django 5.2.2 on 2025-06-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_serial_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="logo",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
