# Generated by Django 5.2.2 on 2025-06-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments_list", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OPD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_date", models.DateField(blank=True, null=True)),
                (
                    "opd_record_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("height", models.CharField(blank=True, max_length=10, null=True)),
                ("weight", models.CharField(blank=True, max_length=10, null=True)),
                ("bp", models.CharField(blank=True, max_length=10, null=True)),
                ("pulse", models.CharField(blank=True, max_length=10, null=True)),
                ("temperature", models.CharField(blank=True, max_length=10, null=True)),
                ("respiration", models.CharField(blank=True, max_length=10, null=True)),
                ("previous_medical_issue", models.TextField(blank=True, null=True)),
                ("symptoms", models.TextField(blank=True, null=True)),
                (
                    "charge_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("charge", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "payment_mode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("paid_amount", models.CharField(blank=True, max_length=50, null=True)),
                ("due_amount", models.CharField(blank=True, max_length=50, null=True)),
                ("live_consult", models.CharField(blank=True, max_length=5, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointments_list.appointment",
                    ),
                ),
            ],
        ),
    ]
