# Generated by Django 5.2.2 on 2025-06-20 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        ("staff_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorchatsession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="staff_management.employee",
            ),
        ),
    ]
