# Generated by Django 5.2.2 on 2025-06-27 07:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0003_alter_bed_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="bed",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bed",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
