# Generated by Django 5.2.2 on 2025-06-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "staff_member_id",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("username", models.CharField(max_length=100, null=True, unique=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("password", models.CharField(max_length=50, null=True)),
                ("dob", models.DateField(null=True)),
                ("gender", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="emp_img/"),
                ),
                ("phone", models.CharField(max_length=15, null=True, unique=True)),
                ("address", models.TextField(null=True)),
                ("city", models.CharField(max_length=100, null=True)),
                ("state", models.CharField(max_length=50, null=True)),
                ("zip_code", models.CharField(max_length=10, null=True)),
                ("aadhar_no", models.CharField(max_length=12, null=True)),
                ("aadhar_front_image", models.TextField(blank=True, null=True)),
                ("aadhar_back_image", models.TextField(blank=True, null=True)),
                ("pan_no", models.CharField(max_length=10, null=True)),
                ("pan_image", models.TextField(blank=True, null=True)),
                ("bank_name", models.CharField(max_length=100, null=True)),
                ("account_no", models.CharField(max_length=50, null=True)),
                ("account_holder_name", models.CharField(max_length=50, null=True)),
                ("ifsc_code", models.CharField(max_length=20, null=True)),
                ("upi_id", models.CharField(max_length=50, null=True)),
                ("other1", models.TextField(max_length=100, null=True)),
                ("other2", models.TextField(max_length=100, null=True)),
                ("latitude", models.CharField(max_length=50, null=True)),
                ("longitude", models.CharField(max_length=50, null=True)),
                ("location", models.CharField(max_length=50, null=True)),
                ("fees", models.CharField(max_length=10, null=True)),
                ("designation", models.CharField(max_length=50, null=True)),
                ("last_login", models.CharField(max_length=50, null=True)),
                ("last_login_ip", models.CharField(max_length=50, null=True)),
                ("notification_token", models.TextField(blank=True, null=True)),
                ("is_active", models.CharField(blank=True, max_length=100, null=True)),
                ("plan_id", models.CharField(max_length=12, null=True)),
                ("plan_expire_date", models.CharField(max_length=10, null=True)),
                ("otp", models.CharField(max_length=5, null=True)),
                ("otp_expire", models.CharField(max_length=10, null=True)),
                ("blood_group", models.CharField(max_length=10, null=True)),
                ("height", models.CharField(max_length=10, null=True)),
                ("weight", models.CharField(max_length=10, null=True)),
                ("languages", models.JSONField(blank=True, null=True)),
                ("services", models.JSONField(blank=True, null=True)),
                ("expertise", models.CharField(max_length=50, null=True)),
                ("service_location", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.role",
                    ),
                ),
            ],
        ),
    ]
