# Generated by Django 5.2.2 on 2025-06-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="employee",
            table="Employee-Management",
        ),
    ]
