# Generated by Django 5.2.2 on 2025-06-27 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff_management", "0003_alter_employee_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="employee",
            table="Employees",
        ),
    ]
