# Generated by Django 5.2.2 on 2025-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DischargeCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "patient_mobile",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "patient_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("discharge_date", models.DateField(blank=True, null=True)),
                ("state", models.CharField(blank=True, max_length=32, null=True)),
                ("pincode", models.CharField(blank=True, max_length=10, null=True)),
                ("district", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("discharge_certificate", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Discharge Certificate",
                "verbose_name_plural": "Discharge Certificates",
                "db_table": "Discharge-Certificates",
                "ordering": ["-created_at"],
            },
        ),
    ]
