# Generated by Django 5.2.2 on 2025-06-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "appointment_record_id",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("fees", models.CharField(max_length=5, null=True)),
                ("shift", models.CharField(blank=True, max_length=50, null=True)),
                ("appointment_date", models.DateField(blank=True, null=True)),
                ("appointment_time", models.TimeField(blank=True, null=True)),
                ("priority", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "payment_mode",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "advance_payment",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "total_payment",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("due_payment", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "aadhar_card_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "ayushman_card_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "aabha_card_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("upi_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "credit_card_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "debit_card_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("bank_name", models.CharField(blank=True, max_length=50, null=True)),
                ("bank_acc_no", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "acc_holder_name",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "insurance_policy_no",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "appointment_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("height", models.CharField(blank=True, max_length=10, null=True)),
                ("weight", models.CharField(blank=True, max_length=10, null=True)),
                ("bp", models.CharField(blank=True, max_length=10, null=True)),
                ("pulse", models.CharField(blank=True, max_length=10, null=True)),
                ("temperature", models.CharField(blank=True, max_length=10, null=True)),
                ("spo2", models.CharField(blank=True, max_length=10, null=True)),
                ("rbs", models.CharField(blank=True, max_length=10, null=True)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "Patient-Appointments",
            },
        ),
        migrations.CreateModel(
            name="Pescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pescription_custom_id",
                    models.CharField(max_length=100, null=True, unique=True),
                ),
                ("prescription", models.JSONField(default=dict)),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "Patient-Prescriptions",
            },
        ),
    ]
