# Generated by Django 5.2.2 on 2025-06-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_list", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="audio_recordings",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
