# Generated by Django 5.2.2 on 2025-06-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_list", "0005_appointment_audio_recordings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="audio_recordings",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
