# Generated by Django 5.2.2 on 2025-06-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_list", "0006_alter_appointment_audio_recordings"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="trasncription",
            field=models.TextField(blank=True, null=True),
        ),
    ]
