# Generated by Django 5.2.2 on 2025-06-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_list", "0008_appointment_soap_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="soap_data",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
