# Generated by Django 5.2.2 on 2025-07-05 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_list", "0009_alter_appointment_soap_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="soap_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
