# Generated by Django 5.2.2 on 2025-06-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments_list", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ipd_record_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("admission_date", models.DateField(blank=True, null=True)),
                ("discharge_date", models.DateField(blank=True, null=True)),
                ("height", models.CharField(blank=True, max_length=10, null=True)),
                ("weight", models.CharField(blank=True, max_length=10, null=True)),
                ("bp", models.CharField(blank=True, max_length=10, null=True)),
                ("pulse", models.CharField(blank=True, max_length=10, null=True)),
                ("temperature", models.CharField(blank=True, max_length=10, null=True)),
                ("respiration", models.CharField(blank=True, max_length=10, null=True)),
                ("symptoms", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("previous_medical_issue", models.TextField(blank=True, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("bed_ward_history", models.JSONField(blank=True, null=True)),
                ("ipd_patient_history", models.JSONField(blank=True, null=True)),
                ("casualty", models.CharField(blank=True, max_length=10, null=True)),
                ("old_patient", models.CharField(blank=True, max_length=10, null=True)),
                ("tpa", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True, default="Admitted", max_length=50, null=True
                    ),
                ),
                ("bed_charge", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "service_charge",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "miscellaneous_charge",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "total_charge",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateField(auto_now_add=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="appointments_list.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "IPD-Data",
            },
        ),
    ]
