# Generated by Django 5.2.2 on 2025-06-20 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("radiology_module", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="radiologytest",
            name="user",
        ),
    ]
