# Generated by Django 5.2.2 on 2025-06-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bed_type", models.CharField(blank=True, max_length=100, null=True)),
                ("bed_number", models.CharField(max_length=20, unique=True)),
                ("ward", models.CharField(blank=True, max_length=100, null=True)),
                ("floor", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "bed_charges",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("bed_status", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_assigned",
                        to="patients.patient",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bed",
                "verbose_name_plural": "Beds",
                "db_table": "bed_setting",
            },
        ),
    ]
