# Generated by Django 5.2.2 on 2025-06-27 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="contactform",
            table="CMS-Contact-Forms",
        ),
        migrations.AlterModelTable(
            name="feature",
            table="CMS-Feature-Section",
        ),
        migrations.AlterModelTable(
            name="footersettings",
            table="CMS-Footer-Settings",
        ),
        migrations.AlterModelTable(
            name="gallery",
            table="CMS-Gallery-Images",
        ),
        migrations.AlterModelTable(
            name="landingpagesection",
            table="CMS-Landing-Page",
        ),
        migrations.AlterModelTable(
            name="menucategory",
            table="CMS-Menubar",
        ),
        migrations.AlterModelTable(
            name="menuitem",
            table="CMS-Menu-Items",
        ),
        migrations.AlterModelTable(
            name="page",
            table="CMS-Pages",
        ),
        migrations.AlterModelTable(
            name="sociallink",
            table="CMS-Social-Links",
        ),
        migrations.AlterModelTable(
            name="usefullink",
            table="CMS-Useful-Links",
        ),
        migrations.AlterModelTable(
            name="websitesettings",
            table="CMS-website-Setting",
        ),
    ]
