# Generated by Django 5.2.2 on 2025-06-20 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "radiology_module",
            "0005_rename_reference_range_radiologytest_female_reference_range_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="radiologytest",
            old_name="female_reference_range",
            new_name="reference_range",
        ),
        migrations.RemoveField(
            model_name="radiologytest",
            name="male_reference_range",
        ),
    ]
