# Generated by Django 5.2.2 on 2025-06-13 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments_list", "0001_initial"),
        ("billing_counter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="billing",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="billings",
                to="billing_counter.billing",
            ),
        ),
    ]
