# Generated by Django 5.2.2 on 2025-06-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments_list", "0007_appointment_trasncription"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="soap_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
